### PR TITLE
Updates readme with new location of Valet drivers

### PR DESCRIPTION
**Pull request by alx-xo**
Valet moved the location of it's folder from `~/.valet/Drivers/` to `~/config/.valet/Drivers/`

https://laravel.com/docs/master/valet#custom-valet-drivers

### CODE REVIEW

**Review by bjuppa — CHANGES_REQUESTED** [review]
Thanks a million for this PR, I hadn't even realised myself that the path to Valet drivers had changed!

Just a small change requested: It seems the new path is `~/.config/valet/Drivers` with a `.` before "config" to hide it. @AnalogMemory can you add that dot before we merge the PR?

**Comment by alx-xo** [comment]
@bjuppa Would it be helpful to note at what version this change happened at (`v2.1.0`) if they happen to be on an older version?

**Comment by bjuppa** [comment]
@AnalogMemory yes, I guess a note about that would help!

**Review by bjuppa — APPROVED** [review]

**Review by bjuppa — APPROVED** [review]

**Review by bjuppa — APPROVED** [review]

**Comment by bjuppa** [comment]
Thanks again @AnalogMemory ! Now that we've come to the point where I'm supposed to merge this excellent PR... I realize I don't have write access to this repo any more 😄 

It has been a while since I was employed by FEW Agency, so I need to get in touch with my former colleagues to gain write access again!

**Comment by bjuppa** [comment]
Thanks @AnalogMemory for this contribution!
And thanks to Veronica @few-machine-user for providing access!

**Comment by alx-xo** [comment]
Thanks y'all :)

**Pull request merged**
